### ISSUE TITLE
Hall of Fame

### ISSUE THREAD

**Issue by mxstbr** [mstoiber/pgp.asc#3]
Discussion about the implementation of a Hall of Fame here!

**Comment by iamwebrocker** [comment]
just a quick 1st brain dump:

### possible ways:
- Auto-discovery (let a crawler find participating websites)
  -- maybe later, too much hassle in the beginning, fiddly error handling etc 
- form with url input where participating people can enter their sites
  -- easy to implement, simple db-or-else storage, but spam-check is needed and a way to verify that indeed a key is placed

**Comment by mxstbr** [comment]
Agree with both points, crawler would be nice but not needed for v1.

I think a form would be the best solution right now. Maybe when they enter the link to their website, the bot could check if the file actually exists. If it does, take the key, then send an encrypted mail (encrypted using the key it just got obv) containing some kind of verification link (similar to E-Mail verification) to the person. If he can decrypt it and click the verification link, we know the file is there and contains a key. 

Possible?

**Comment by rauberdaniel** [comment]
@mstoiber Sounds like a good plan. As far as I can see, you’re currently using Github Pages to publish the site. Are there any plans yet on which technologies to use for the automatic verification, where to host it etc.?

**Comment by mxstbr** [comment]
Yes we are, and there currently are no plans whatsoever. If you have any
ideas/recommendations, please post them!

**Comment by rauberdaniel** [comment]
Well, I don’t want to make any decision, but as a basis for the discussion I’d suggest to use node.js (also, because it might be easier to create a crawler with node.js than with PHP in the future) along with any database (MySQL, SQLite, MongoDB, CouchDB,... I don’t really know what would make the most sense here). I guess it also depends on where it will be hosted. Personally I prefer [Uberspace](https://uberspace.de), but feel free to suggest anything else.

**Comment by mxstbr** [comment]
@rauberdaniel What about adapting something like [this](http://codeforgeek.com/2014/07/node-email-verification-script/) in combination with [this](https://github.com/NodePrime/ursa) and a GET request to `submittedurl.com/pgp.asc`? Would that be possible/feasible, and could you build it? (I have no idea about back-end stuff... you can of course decide about hosting and technologies if nobody else has a better idea , maybe @iamwebrocker has something to say?)

**Comment by floriangosse** [comment]
Like @rauberdaniel I prefer Uberspace, too.
@mstoiber the solution you described schould be possible. For a first version a simple json file can be used to store the perople/websites.

**Comment by mxstbr** [comment]
EDIT 07.01.: Added @floriangosse and @rauberdaniel as contributors and gave them access to our Uberspace via SSH keys. Please keep the discussion in here, and open a new branch from gh-pages for the backend development!

**Comment by floriangosse** [comment]
@rauberdaniel what is your opinion about the links of @mstoiber? I will test NodePrime/ursa in the next days
To store the data I would use json for the first time or do you think we should use a database?

**Comment by rauberdaniel** [comment]
@floriangosse ursa looks like the module everybody uses and looks good to me at first sight. I’ll play around with it in the next days. _(Edit: [openPGP](https://www.npmjs.com/package/openpgp) looks more like the thing we want. Couldn’t yet figure out how ursa fits..)_ Nodemailer is the module I had in mind to send mails. I’ve already used it a little and it worked well. We can then simply use the uberspace SMTP server.

I think it’s safer to use a database (we could use MySQL, since there is one available at uberspace anyway) to store the data and offers more flexibility on how we can then use it. In the long term we would have to use a database anyway.
But of course, this is somewhat more annoying than just reading and writing a json file...

**Comment by floriangosse** [comment]
@rauberdaniel openPGP looks good. I'll play around with both at the weekend.

To choose the database we should define the structure of data we want to save.
I think about following:
- url
- owner
- (?) alternative path of public key (use link element in head)

**Comment by mxstbr** [comment]
Anything to report so far? :smile_cat: Have you decided what utilities you are going to use?

**Comment by rauberdaniel** [comment]
@floriangosse Since we wanted that people have to confirm their key, we should also have a boolean whether it was confirmed and some ID, which can not be guessed or constructed from domain or anything (for the confirmation link).

Also, a date when the key was added (and maybe we can get the date of expiration) would make sense imho.

**Comment by iamwebrocker** [comment]
Hi, these are the db fields I think may be useful:
- ID (internal,autoincrement)
- KeyID (fingerprint?)
- KeyConfirmHash
- KeyConfirmed (bool)
- KeyValidUntil
- KeyURL (unsure, b/c we expect the key under domain/pgp.asc, nevertheless this could be useful for other keynames/formats in future)
- OwnerName (opt)
- OwnerURL (opt, website)
- OwnerMail (opt, email)
- DateCreated (timestamp)
- DateModified (timestamp, onupdate now())
- Deleted (bool)

cheers, tom

**Comment by rauberdaniel** [comment]
@iamwebrocker :+1:

**Comment by iamwebrocker** [comment]
upon rethinking… maybe it would be smart(er) to have owners and keys tables - since one owner may has several keys (in future? - but isn't the whole idea to have the _one_ key, dunno…) anyways, a more normalized structure may be more future-proof?

Keys:
- ID (internal,autoincrement)
- KeyID (fingerprint?)
- KeyConfirmHash
- KeyConfirmed (bool)
- KeyValidUntil
- KeyURL (unsure, b/c we expect the key under domain/pgp.asc, nevertheless this could be useful for other keynames/formats in future)
- DateCreated (timestamp)
- DateModified (timestamp, onupdate now())
- Deleted (bool)

Owners:
- ID
- OwnerName (opt)
- OwnerURL (opt, website)
- OwnerMail (opt, email)
- DateCreated (timestamp)
- DateModified (timestamp, onupdate now())
- Deleted (bool)

Keys-Owners:
- ID
- KeyID (keys.ID)
- OwnerID (owner.ID)

overkill?

**Comment by mxstbr** [comment]
@iamwebrocker we need OwnerName and OwnerURL, those can't be optional. That's the only thing that should be mentioned in the Hall of Fame. We can get the Mail from the Key, and we need that one as well, otherwise we can't send a verification link to them.

I went ahead and created an EER Diagram how it might look (I'm still pretty new to databases, if I did something wrong please correct me):

![Database EER Diagram](https://cloud.githubusercontent.com/assets/7525670/5695703/4cb469ca-99af-11e4-8d8d-18acea642c1c.png)

I think we can take the Fingerprint as KeyID, as the chance for a fingerprint being similar to another one are basically non-existant. 

EDIT: we posted basically at the same time Tom, I had a similar idea! Afaik, the Keys-Owners Relation Table doesn't need an ID, you simply take the KID in combination with PID.

**Comment by iamwebrocker** [comment]
@mstoiber :+1: 
:-)

**Comment by floriangosse** [comment]
@mstoiber We can use the mail from the key if there is only one mail address available but if there are multiple addresses we should ask which address should be used.

**Comment by mxstbr** [comment]
@floriangosse makes sense.

**Comment by floriangosse** [comment]
Is is correct that an entry can't deleted only archived?

We can also use a NoSQL database like MongoDB then we have only a single collection:

**Person**
- name : _String_
- url : _String_
- mail : _String_
- key : _Object_
  - fingerprint : _String_
  - validUntil : _Date_
  - created : _Date_
  - modified : _Date_
  - confirmHash: _String_
  - confirmed: _Boolean_
  - deleted: _boolean_

**Comment by iamwebrocker** [comment]
@floriangosse @mstoiber ID, mail, and comment all are optional when creating a key, so we can't be sure if that info is provided, although most public keys will have id or email in order to be search/findable.

**Comment by mxstbr** [comment]
@iamwebrocker then we have to ask for the mail, otherwise we can hardly send a confirmation mail.

**Comment by floriangosse** [comment]
@iamwebrocker @mstoiber I think we should to it dynamically and ask the user for the mail address if the public key doesn't provide some one.

**Comment by iamwebrocker** [comment]
@mstoiber 
"Afaik, the Keys-Owners Relation Table doesn't need an ID, you simply take the KID in combination with PID."

right, but sometimes it's better to have an internal incremental id for the rows - ie if you want to quickly find the newest entries etc, so I made it a habit to have this ID column in my tables, even if it is not strictly required, but I think that's more personal style than best practise :)

**Comment by mxstbr** [comment]
@floriangosse no `if`, we do ask for the e-mail they want the confirmation link sent to. Many tutorials advise to enter a fake mail address, so I guess many people do that. I'd rather just ask than send it to the wrong e-mail.

@iamwebrocker alright then :)

**Comment by rauberdaniel** [comment]
@mstoiber If key has an e-mail address, ask for confirmation (or pre-filled form field), otherwise ask for input. It should be made obvious that this email will be used for a confirmation mail and therefore should be filled correctly.

**Comment by floriangosse** [comment]
@rauberdaniel @mstoiber This is the solution which I think about.

**Comment by iamwebrocker** [comment]
@floriangosse "Is is correct that an entry can't deleted only archived?"

not sure about that one. the 'deleted' column may act as a safeguard against accidental deletion, perhaps we can delay the real deletion and drop rows with deleted=true via script overnight.
or, since we have a kind of login (?) with mail address and publickey, let the owner decide.

**Comment by mstoiber** [comment]
Any progress here? :smiley: Hows the script coming along?

**Comment by mxstbr** [comment]
# The backend is almost done

Since there didn't seem to be much progress on this, and I'm learning Rails, I built the backend myself using it. You can find the new, dynamic (_yey_) pgp.asc in the branch `feature/backend`. 

Currently the form in the footer sends an email with a verification link to the submitter. When the correct verification link is opened, the `confirmed` attribute is set to true and the person will show up in the Hall of Fame.

Notes: 
- E-Mail encryption is **not working** yet, the verification email is currently sent in plain text. This has to do with me not getting the gem to encrypt the mail working, but I've contacted the creator and that should be fixed very soon.
- I chose to ask for the mail address in the form, because the other idea is too elaborate currently.
- I had to change the database schema a bit (moved the `confirm_hash` and the `confirmed` boolean to the `person` database, because the persons need to be confirmed and not the keys for the hall of fame), and I'm currently debating not even saving the keys. (I don't currently, but the structure would be there) We don't need them because if we need to send an email we can get the key from the website anyway.
- Setup instructions can now be found in the README of that branch, but I'll repost them below for ease of access: 

## Getting up and running

This assumes you have Ruby, Rails and all the needed utilities (git, bundle, bower) installed. If you get any errors during this setup, please refer to your search engine for help! If you still cannot figure it out, contact me on [twitter](http://mxs.is/@).
- Clone the repo to your local machine using `git clone git@github.com:mstoiber/pgp.asc.git`.
- Start a PostgreSQL instance. (E.g. on Mac: `postgres -D /usr/local/var/postgres`)
- Open the terminal and change into the pgp.asc folder.
- Run `bundle install`.
- Run `bower install`.
- Open another instance/tab of the terminal and run `mailcatcher`.
- Run `rake db:create`, followed by `rake db:migrate`.
- Run `rails server`, and go to `http://localhost:3000` to see the site! If you send an email through the form, you can find it at `http://127.0.0.1:1080/`. (This is mailcatcher, it literally catches the mails)

## Project Structure

If you want to edit the frontend, ignore everything except the `app` folder. In there you should focus on the `assets` (Stylesheets, Scripts and Images) and the `views/persons` folder. (The actual HTML files you see)

For the backend, all the important logic is in the Persons Controller (`app/controllers/persons_controller.rb`) and the Person Model. (`app/models/person.rb`)

If you are looking for something but can't find it, contact me on [twitter](http://mxs.is/@).

**Comment by mxstbr** [comment]
The new website is online! Check it out and add yourself to the Hall Of Fame: http://pgpasc.org

I'll start refactoring the git repo, will hopefully get the master branch up to date today.
